"""
Request schemas (Pydantic).

Pydantic models for request validation and serialization.
"""

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, ConfigDict, field_validator
from app.core.validation import sanitize_text
from app.models.request import RequestStatus


class RequestBase(BaseModel):
    """Base Request schema with common fields."""
    title: str = Field(..., min_length=1, max_length=200, description="Request title")
    description: Optional[str] = Field(None, max_length=2000, description="Detailed description")
    
    @field_validator('title')
    @classmethod
    def sanitize_title(cls, v: str) -> str:
        """Sanitize title to prevent XSS attacks."""
        # Don't pass max_length here - let Field validation handle it
        sanitized = sanitize_text(v)
        if not sanitized or not sanitized.strip():
            raise ValueError("Title cannot be empty after sanitization")
        return sanitized
    
    @field_validator('description')
    @classmethod
    def sanitize_description(cls, v: Optional[str]) -> Optional[str]:
        """Sanitize description to prevent XSS attacks."""
        if v is None:
            return None
        # Don't pass max_length here - let Field validation handle it
        return sanitize_text(v)


class RequestCreate(RequestBase):
    """
    Schema for creating a new request.
    
    The reference, status, and submitted_at are auto-generated by the system.
    """
    submitted_by: str = Field(..., min_length=1, max_length=100, description="Employee identifier")
    
    @field_validator('submitted_by')
    @classmethod
    def sanitize_submitted_by(cls, v: str) -> str:
        """Sanitize submitted_by field."""
        # Don't pass max_length here - let Field validation handle it
        sanitized = sanitize_text(v)
        if not sanitized or not sanitized.strip():
            raise ValueError("submitted_by cannot be empty after sanitization")
        return sanitized


class RequestUpdate(BaseModel):
    """
    Schema for updating an existing request.
    
    All fields are optional for partial updates.
    """
    status: Optional[str] = Field(None, description="New status (submitted, reviewing, approved, completed, rejected)")
    public_notes: Optional[str] = Field(None, max_length=1000, description="Notes visible to employee")
    internal_notes: Optional[str] = Field(None, max_length=2000, description="HR-only notes")
    reviewed_by: Optional[str] = Field(None, max_length=100, description="HR staff identifier")
    
    @field_validator('status')
    @classmethod
    def validate_status(cls, v: Optional[str]) -> Optional[str]:
        """Validate status is one of the allowed values."""
        if v is None:
            return None
        # Use RequestStatus enum values for validation
        allowed_statuses = [status.value for status in RequestStatus]
        v_lower = v.lower().strip()
        if v_lower not in allowed_statuses:
            raise ValueError(f"Status must be one of: {', '.join(allowed_statuses)}")
        return v_lower
    
    @field_validator('public_notes', 'internal_notes')
    @classmethod
    def sanitize_notes(cls, v: Optional[str]) -> Optional[str]:
        """Sanitize notes fields to prevent XSS attacks."""
        if v is None:
            return None
        # Don't pass max_length here - let Field validation handle it
        return sanitize_text(v)
    
    @field_validator('reviewed_by')
    @classmethod
    def sanitize_reviewed_by(cls, v: Optional[str]) -> Optional[str]:
        """Sanitize reviewed_by field."""
        if v is None:
            return None
        # Don't pass max_length here - let Field validation handle it
        return sanitize_text(v)


class RequestResponse(RequestBase):
    """
    Schema for request response.
    
    Note: internal_notes is NOT included in public responses.
    """
    model_config = ConfigDict(from_attributes=True)
    
    id: int
    reference: str
    status: str
    submitted_by: str
    submitted_at: datetime
    reviewed_by: Optional[str] = None
    reviewed_at: Optional[datetime] = None
    public_notes: Optional[str] = None
    created_at: datetime
    updated_at: datetime
