"""
Request schemas (Pydantic).

Pydantic models for request validation and serialization.
"""

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, ConfigDict


class RequestBase(BaseModel):
    """Base Request schema with common fields."""
    title: str = Field(..., max_length=200, description="Request title")
    description: Optional[str] = Field(None, max_length=2000, description="Detailed description")


class RequestCreate(RequestBase):
    """
    Schema for creating a new request.
    
    The reference, status, and submitted_at are auto-generated by the system.
    """
    submitted_by: str = Field(..., max_length=100, description="Employee identifier")


class RequestUpdate(BaseModel):
    """
    Schema for updating an existing request.
    
    All fields are optional for partial updates.
    """
    status: Optional[str] = Field(None, description="New status (submitted, reviewing, approved, completed, rejected)")
    public_notes: Optional[str] = Field(None, description="Notes visible to employee")
    internal_notes: Optional[str] = Field(None, description="HR-only notes")
    reviewed_by: Optional[str] = Field(None, max_length=100, description="HR staff identifier")


class RequestResponse(RequestBase):
    """
    Schema for request response.
    
    Note: internal_notes is NOT included in public responses.
    """
    model_config = ConfigDict(from_attributes=True)
    
    id: int
    reference: str
    status: str
    submitted_by: str
    submitted_at: datetime
    reviewed_by: Optional[str] = None
    reviewed_at: Optional[datetime] = None
    public_notes: Optional[str] = None
    created_at: datetime
    updated_at: datetime
